### ISSUE TITLE
t5-large 精度差异

### ISSUE THREAD

**Issue by ShaneTian** [JunnYu/paddle_t5#1]
比 small 和 base 稍微大一点
```
mean difference: tensor(9.9235e-07)
max difference: tensor(0.0001)
```

**Comment by JunnYu** [comment]
这可能是因为`paddle`跟`pytorch`之间`nn.Linear`和`matmul`不能完全对齐，从而导致误差不断累积。之前我就提过关于这个的问题，https://github.com/PaddlePaddle/Paddle/issues/35123 、https://github.com/PaddlePaddle/Paddle/issues/35819 并且还有其他用户也同样反映过有关这个的问题。
Tips: 这个误差在实际使用的时，感觉是可以忽略的。

**Comment by ShaneTian** [comment]
好的，多谢。
发现使用 `paddlenlp=2.2.5` 版本和本代码库，比较精度差异结果不一样，且差距非常大，请问是什么原因呢？
详见：https://github.com/PaddlePaddle/PaddleNLP/issues/1901

**Comment by JunnYu** [comment]
你把两个代码都放在cpu上进行比较，然后再试试都在gpu上比较。paddle默认使用的是gpu

**Comment by ShaneTian** [comment]
确实，在 CPU 上，精度差异非常小。**但是在 GPU 上，Paddle 和 PyTorch 差距还是比较大的。**

> 以 `T5Model` 为例，`T5ForConditionalGeneration` 结论类似。

### CPU
`t5-small`
```
mean decoder hidden difference: 1.2361211e-07
max decoder hidden difference: 1.5258789e-05
```

`t5-base`
```
mean decoder hidden difference: 3.1235538e-07
max decoder hidden difference: 2.7656555e-05
```

`t5-large`
```
mean decoder hidden difference: 9.923486e-07
max decoder hidden difference: 0.000101327896
```

对比脚本修改：
```py
paddle.set_device("cpu")
```

### GPU
`t5-small`
```
mean decoder hidden difference: 7.532996e-05
max decoder hidden difference: 0.0073661804
```

`t5-base`
```
mean decoder hidden difference: 0.00012183325
max decoder hidden difference: 0.0052900314
```

`t5-large`
```
mean decoder hidden difference: 0.00020994102
max decoder hidden difference: 0.009232521
```

对比脚本修改：
```py
pd_model.to("gpu:0")
pt_model.cuda()

_dummy_inputs = {
    "decoder_input_ids": input_ids.cuda(),
    "input_ids": input_ids.cuda(),
    "decoder_attention_mask": input_mask.cuda()
}

pd_decoder_hidden = pd_outputs[0].cpu().numpy()
pt_decoder_hidden = pt_outputs.last_hidden_state.cpu().numpy()
```

**Comment by JunnYu** [comment]
所以这主要的原因还与GPU设备有关的，比如显卡类型、Cuda版本等等。

**Comment by ShaneTian** [comment]
- python==3.7.10
- torch==1.10.2+cu111
- paddlepaddle-gpu==2.2.2.post111
- transformers==4.17.0

显卡是 A100-SXM4-40GB，torch 和 paddle 的 CUDA 版本都是 11.1
请问有什么办法吗？

**Comment by JunnYu** [comment]
没啥好办法，当时我在30系列显卡上就发现误差很大了，V100上可能好一点。

**Comment by ShaneTian** [comment]
好的，多谢。
